3 6 3:00

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -114,31 +114,27 @@ ubuntu@$APP_IP:/home/ubuntu/
 
 ssh -o StrictHostKeyChecking=no \
 -i /tmp/master.pem ubuntu@$APP_IP << EOF
+sudo mkdir -p /data
+
+if ! mountpoint -q /data; then
+
+    if ! blkid /dev/nvme1n1 > /dev/null 2>&1; then
+        sudo mkfs.ext4 /dev/nvme1n1
+    fi
+
+    sudo mount /dev/nvme1n1 /data
+
+    grep -q "/data " /etc/fstab || \
+    echo '/dev/nvme1n1 /data ext4 defaults,nofail 0 2' | sudo tee -a /etc/fstab
+fi
+
 sudo mkdir -p /data/ghost
 sudo mkdir -p /data/mysql
-if ! mountpoint -q /data/ghost; then
 
-    if ! blkid /dev/nvme1n1 > /dev/null 2>&1; then
-        sudo mkfs.ext4 /dev/nvme1n1
-    fi
-
-    sudo mount /dev/nvme1n1 /data/ghost || true
-
-    grep -q "/data/ghost" /etc/fstab || \
-    echo '/dev/nvme1n1 /data/ghost ext4 defaults,nofail 0 2' | sudo tee -a /etc/fstab
-fi
-
-if ! mountpoint -q /data/mysql; then
-
-    if ! blkid /dev/nvme1n1 > /dev/null 2>&1; then
-        sudo mkfs.ext4 /dev/nvme1n1
-    fi
-
-    sudo mount /dev/nvme1n1 /data/mysql || true
-
-    grep -q "/data/mysql" /etc/fstab || \
-    echo '/dev/nvme1n1 /data/mysql ext4 defaults,nofail 0 2' | sudo tee -a /etc/fstab
-fi
+sudo chown -R 999:999 /data/mysql
+sudo chmod -R 755 /data/mysql
+sudo chown -R 999:999 /data/ghost
+sudo chmod -R 755 /data/ghost
 rm -rf app
 
 git clone https://github.com/koushiksiripuram/end_to_end.git app
