12:00

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -114,7 +114,19 @@ ubuntu@$APP_IP:/home/ubuntu/
 
 ssh -o StrictHostKeyChecking=no \
 -i /tmp/master.pem ubuntu@$APP_IP << EOF
+sudo mkdir -p /data/ghost
 
+if ! mountpoint -q /data/ghost; then
+
+    if ! blkid /dev/nvme1n1 > /dev/null 2>&1; then
+        sudo mkfs.ext4 /dev/nvme1n1
+    fi
+
+    sudo mount /dev/nvme1n1 /data/ghost || true
+
+    grep -q "/data/ghost" /etc/fstab || \
+    echo '/dev/nvme1n1 /data/ghost ext4 defaults,nofail 0 2' | sudo tee -a /etc/fstab
+fi
 rm -rf app
 
 git clone https://github.com/koushiksiripuram/end_to_end.git app
